version: "3"

services:
  mysql:
    image: mysql:8.0.16
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: votedb
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - local-db:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  local-db: